name: artifacts
on: workflow_dispatch
jobs:
    job-artifact:
        runs-on: ubuntu-latest
        steps:
            - name: artifacts
              uses: actions/upload-artifact@v4
              with:
                name: node-modules
                path: node_modules
            - name: download_artifacts
              uses: actions/download-artifact@v4
              with:
                name: node-modules
              
