name: artifacts
on: push
jobs:
    job-artifact:
        runs-on: ubuntu-latest
        outputs:
            script-print: ${{steps.publish.outputs.script-file}}
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - run: npm install
            - name: artifacts
              uses: actions/upload-artifact@v4
              with:
                name: node-modules
                path: node_modules
            - name: download_artifacts
              uses: actions/download-artifact@v4
              with:
                name: node-modules
            - name: output-getting
              id: publish
              #run: find . -type f -name "*.html" -exec echo '::set-output name=script-file::{}'
             # run: find . -type f -name "*.txt" -exec echo 'script-file={} >> $GITHUB_OUTPUTS ' \;
              #run: find . -type f -name "*.html" -execdir echo 'script-file={} >>$GITHUB_OUTPUTS' \;
              #run: html_files=$(find . -type f -name "*.html" -exec echo 'script-file={}' \;) echo "script-file=$html_files" >> $GITHUB_ENV
              run: find . -type f -name "*.html" -execdir echo "::set-output name=script-file::{}" \;
    job-outputs:
        needs: job-artifact
        runs-on: ubuntu-latest
        steps:
            - name: outputs-outside
              run: echo "${{needs.job-artifact.outputs.script-print}}"
              
