name: artifacts
on: push
jobs:
    job-artifact:
        runs-on: ubuntu-latest
        outputs:
            script-print: ${{steps.publish.outputs.script-file}}
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - run: npm install
            - name: artifacts
              uses: actions/upload-artifact@v4
              with:
                name: node-modules
                path: node_modules
            - name: download_artifacts
              uses: actions/download-artifact@v4
              with:
                name: node-modules
            - name: output-getting
              id: publish
              run: find . -type f -name "*.txt" -exec echo 'script-file={} >> $GITHUB_OUTPUTS ' \;
    job-outputs:
        needs: job-artifact
        runs-on: ubuntu-latest
        steps:
            - name: outputs-outside
              run: echo "${{needs.job-artifact.outputs.script-print}}"
              
