name: activity types and Event filters
on: 
    pull_request:
        branches: main  #branch filter
        types: closed #activity types
        paths-ignore: '.github/workflows/*'
    push:
      branches: main
     # paths-ignore: '.github/workflows/*'
jobs:
    jobs-1:
        runs-on: ubuntu-latest        
        steps:
        - uses: actions/checkout@v4
        - name: show working directory
          run: ls -l
        - run: pwd
        - run: mkdir santhosh
        - run: ls -l 
