name: activity types and Event filters
on: 
    pull_request:
        branches: main
        types: closed
jobs:
    jobs-1:
        runs-on: ubuntu-latest        
        steps:
        - uses: actions/checkout@v4
        - name: show working directory
          run: ls -l
        - run: pwd
