name: artifacts-2

on: push

jobs:
  job-artifact-2:
    runs-on: ubuntu-latest
    outputs:
      script-print: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Upload Node Modules
        uses: actions/upload-artifact@v4
        with:
          name: node-modules
          path: node_modules

      - name: Download Node Modules
        uses: actions/download-artifact@v4
        with:
          name: node-modules

      - name: Find and Set Outputs
        id: publish
        run: |
          # Find all .html files and set output
          html_files=$(find . -type f -name "*.html" -exec echo 'script-file={}' \;)
          echo "script-file=$html_files" >> $GITHUB_ENV

  job-outputs:
    needs: job-artifact-2
    runs-on: ubuntu-latest
    steps:
      - name: Output from Previous Job
        run: echo "${{ needs.job-artifact-2.outputs.script-print }}"
